device:
  pressure:
    offset: 12.73
    scale: 0.0126
  flow:
    offset: 0.0
    scale: 0.7198


rotary-live:
  Log Filename:
    type: Filename
    name: Log filename

  Sensor ID:
    type: Incr
    name: Sensor ID
    default: 1
    min: 1
    max: 20
    incr: 1

  Current Setting:
    type: Current
    default: 3
    items: [1, 3, 5, 10, 20, 30]

rotary:
  AvgWindow:
    type: Selection
    name: Average Window
    lcd_name: AvgWindow
    default: 3
    items: [1, 3, 5, 10, 20, 30]
    unit: sec
