device:
  pressure:
    offset: 12.73
    scale: 0.0126
  flow:
    offset: 0.0
    scale: 0.7198

global:
  debug: false
  analyze-every: 3 # seconds
  save-every: 20 # seconds
  cumulative-every: 10 # seconds
  run-every: 0.5 # seconds
  window-size: 1500 # 30 seconds @ 50 hertz

rotary-live:
  Log Filename:
    type: Filename
    name: Log filename

  Reset Setting:
    type: Reset
    name: Turn to Reset

  Current Setting:
    type: Current
    default: 3
    items: [1, 3, 5, 10, 20, 30]

rotary:
  AvgWindow:
    type: Selection
    name: Average Window
    lcd_name: Avg Window
    default: 3
    items: [1, 3, 5, 10, 20, 30]
    unit: sec

  Sensor ID:
    type: Incr
    name: Sensor ID
    default: 1
    min: 1
    max: 24
    incr: 1
