from typing import TypeVar, Type, overload, AnyStr, Union
from os import PathLike

T = TypeVar("T")
Path = Union[AnyStr, PathLike[AnyStr]]

class ConfigView:
    def __getitem__(self, item: str) -> "ConfigView": ...
    @overload
    def get(self) -> str: ...
    @overload
    def get(self, template: Type[T]) -> T: ...

class Configuration:
    def __init__(self, appname: str, modname: str = None, read: bool = True): ...
    def set_file(self, filename: Path) -> None: ...
    def clear(self) -> None: ...
    def __getitem__(self, item: str) -> ConfigView: ...
