from typing import List, Tuple

class Handle: ...

class pi:
    connected: bool
    def __init__(self, host: str = None, port : int = None, show_errors : bool = False): ...
    def i2c_open(self, i2c_bus : int , i2c_address : int, i2c_flags = 0) -> Handle: ...
    def i2c_write_device(self, handle: Handle, data: List[int]): ...
    def i2c_read_device(self, handle: Handle, nbytes: int ) -> Tuple[int, bytearray]: ...

    def i2c_close(self, handle: Handle): ...
    def stop(self): ...
    def set_PWM_dutycycle(self, user_gpio: int, dutycycle: int): ...
