from typing import Any, Iterable, Tuple, List

SUB: int
SUBSCRIBE: int
PUB: int

class Socket:
    def setsockopt_string(self, _1: int, _2: str): ...
    def send_string(self, _: str): ...
    def send_json(self, _: Any): ...
    def connect(self, _: str): ...
    def bind(self, _: str): ...
    def recv_json(self) -> Any: ...

class Context:
    def socket(self, _: int) -> Socket: ...

def select(
    rlist: Iterable[Socket],
    wlist: Iterable[Socket],
    xlist: Iterable[Socket],
    timeout=None,
) -> Tuple[List[Socket], List[Socket], List[Socket]]: ...
